USE [master]
GO
/****** Object:  Database [Exercise Log]    Script Date: 4/2/2023 9:38:52 AM ******/
CREATE DATABASE [Exercise Log]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Exercise Log', FILENAME = N'C:\Users\thema\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\Exercise Log_Primary.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Exercise Log_log', FILENAME = N'C:\Users\thema\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\Exercise Log_Primary.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Exercise Log] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Exercise Log].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Exercise Log] SET ANSI_NULL_DEFAULT ON 
GO
ALTER DATABASE [Exercise Log] SET ANSI_NULLS ON 
GO
ALTER DATABASE [Exercise Log] SET ANSI_PADDING ON 
GO
ALTER DATABASE [Exercise Log] SET ANSI_WARNINGS ON 
GO
ALTER DATABASE [Exercise Log] SET ARITHABORT ON 
GO
ALTER DATABASE [Exercise Log] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Exercise Log] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Exercise Log] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Exercise Log] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Exercise Log] SET CURSOR_DEFAULT  LOCAL 
GO
ALTER DATABASE [Exercise Log] SET CONCAT_NULL_YIELDS_NULL ON 
GO
ALTER DATABASE [Exercise Log] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Exercise Log] SET QUOTED_IDENTIFIER ON 
GO
ALTER DATABASE [Exercise Log] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Exercise Log] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Exercise Log] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Exercise Log] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Exercise Log] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Exercise Log] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Exercise Log] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Exercise Log] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Exercise Log] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Exercise Log] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Exercise Log] SET  MULTI_USER 
GO
ALTER DATABASE [Exercise Log] SET PAGE_VERIFY NONE  
GO
ALTER DATABASE [Exercise Log] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Exercise Log] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Exercise Log] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [Exercise Log] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Exercise Log] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [Exercise Log] SET QUERY_STORE = OFF
GO
USE [Exercise Log]
GO
/****** Object:  Table [dbo].[Entry]    Script Date: 4/2/2023 9:38:53 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Entry](
	[EntryId] [int] NOT NULL,
	[ExerciseGoalId] [int] NOT NULL,
	[EntryDate] [datetime] NOT NULL,
	[HoursExercised] [int] NOT NULL,
	[MinutesExercised] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[EntryId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Exercise]    Script Date: 4/2/2023 9:38:53 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Exercise](
	[ExerciseId] [int] NOT NULL,
	[ExerciseName] [varchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ExerciseId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ExerciseGoal]    Script Date: 4/2/2023 9:38:53 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ExerciseGoal](
	[ExerciseGoalId] [int] NOT NULL,
	[ExerciseId] [int] NOT NULL,
	[UserId] [int] NOT NULL,
	[Goal] [varchar](5) NOT NULL,
	[Total] [varchar](5) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ExerciseGoalId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[User]    Script Date: 4/2/2023 9:38:53 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[UserId] [int] NOT NULL,
	[UserFirstName] [varchar](100) NOT NULL,
	[UserLastName] [varchar](100) NOT NULL,
	[UserName] [varchar](100) NOT NULL,
	[UserPasswordHash] [varchar](100) NOT NULL,
	[Salt] [varchar](25) NOT NULL,
	[LastLogIn] [datetime] NOT NULL,
	[DateJoined] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Entry]  WITH CHECK ADD  CONSTRAINT [FK_Entry_ExerciseGoal] FOREIGN KEY([ExerciseGoalId])
REFERENCES [dbo].[ExerciseGoal] ([ExerciseGoalId])
GO
ALTER TABLE [dbo].[Entry] CHECK CONSTRAINT [FK_Entry_ExerciseGoal]
GO
ALTER TABLE [dbo].[ExerciseGoal]  WITH CHECK ADD  CONSTRAINT [FK_ExerciseGoal_Exercise] FOREIGN KEY([ExerciseId])
REFERENCES [dbo].[Exercise] ([ExerciseId])
GO
ALTER TABLE [dbo].[ExerciseGoal] CHECK CONSTRAINT [FK_ExerciseGoal_Exercise]
GO
ALTER TABLE [dbo].[ExerciseGoal]  WITH CHECK ADD  CONSTRAINT [FK_ExerciseGoal_User] FOREIGN KEY([UserId])
REFERENCES [dbo].[User] ([UserId])
GO
ALTER TABLE [dbo].[ExerciseGoal] CHECK CONSTRAINT [FK_ExerciseGoal_User]
GO
USE [master]
GO
ALTER DATABASE [Exercise Log] SET  READ_WRITE 
GO
